name: Rust

on: [push]

jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: >
        cargo build --all --release && 
        strip target/release/bj_rs_test && 
        mv target/release/bj_rs_test target/release/bj_rs_test_x86_64

  build-linux-arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: > 
          cargo build --all --release && 
          strip target/release/bj_rs_test && 
          mv target/release/bj_rs_test target/release/bj_rs_test_arm64